### ISSUE TITLE
Will it be rejected by using [self.navigationBar valueForKey:@"_backgroundView"] ?

### ISSUE THREAD

**Issue by jaybowang** [AustinChou/Apple-Music-Navigation-Bar#1]
Thank you so much for sharing this awesome code.I want it for quite a while. 👍

And I have one question. Will apps be rejected by using `[self.navigationBar valueForKey:@"_backgroundView"]`? I think it's a private API and Apple won't allow us to do this. 
Have you tried this in your App Store apps?

**Comment by evianzhow** [comment]
@jaybowong https://github.com/MoZhouqi/KMNavigationBarTransition Use this repo instead. 
And the answer to your question: https://github.com/MoZhouqi/KMNavigationBarTransition/issues/7
TL:DR; => NO;

**Comment by jaybowang** [comment]
Thanks!!
